"use client";

import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { adminService, type AdminCategoryResponse, type CampaignResponse } from "@/features/admin/services/admin-service";

const iso = (days = 0) => { const d = new Date(); d.setDate(d.getDate() - days); return d.toISOString().slice(0, 10); };

export default function AdminCampaignsPage() {
  const [categories, setCategories] = useState<AdminCategoryResponse[]>([]);
  const [categoryId, setCategoryId] = useState("");
  const [offerText, setOfferText] = useState("15% de descuento por tiempo limitado");
  const [subject, setSubject] = useState("Descubre las piezas favoritas de esta colección");
  const [startDate, setStartDate] = useState(iso(30)); const [endDate, setEndDate] = useState(iso());
  const [response, setResponse] = useState<CampaignResponse | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { adminService.getCategories().then(data => { setCategories(data); setCategoryId(String(data[0]?.categoryId ?? "")); }); }, []);
  const request = () => ({ categoryId: Number(categoryId), offerText, subject: subject.trim(), startDate, endDate });
  const cards = useMemo(() => response?.products.map(p => `<div style="padding:14px 0;border-bottom:1px solid #eadbd0"><strong>${p.name}</strong><span style="float:right;color:#7f4c31">S/ ${Number(p.price).toFixed(2)}</span></div>`).join("") ?? "", [response]);
  const preview = response?.htmlPreview.replaceAll("{{emailTitle}}", response.subject).replaceAll("{{customerName}}", "Cliente de prueba").replaceAll("{{categoryName}}", response.categoryName).replaceAll("{{offerText}}", offerText).replaceAll("{{productCards}}", cards);
  const previewCampaign = async (e: React.FormEvent) => { e.preventDefault(); if (!categoryId) return toast.error("Selecciona una categoría"); try { setBusy(true); setResponse(await adminService.previewCampaign(request())); toast.success("Análisis y vista previa generados"); } catch (err) { toast.error(err instanceof Error ? err.message : "No se pudo generar"); } finally { setBusy(false); } };
  const send = async () => { if (!response) return; try { setBusy(true); const result = await adminService.sendCampaign(request()); setResponse(result); toast.success(`Campaña enviada a ${result.recipients} clientes`); } catch (err) { toast.error(err instanceof Error ? err.message : "No se pudo enviar"); } finally { setBusy(false); } };

  return <div className="grid gap-6 lg:grid-cols-[420px_1fr]"><section><h1 className="text-3xl font-bold">Campaña inteligente</h1><p className="mt-2 text-sm text-slate-500">Selecciona una categoría; el sistema elige hasta tres productos con mayor puntuación por vistas, carrito y favoritos.</p><form onSubmit={previewCampaign} className="mt-6 space-y-4 rounded-xl border bg-white p-5 shadow-sm"><label className="grid gap-2 text-sm font-semibold">Categoría<select value={categoryId} onChange={e => { setCategoryId(e.target.value); setResponse(null); }} className="rounded-lg border px-3 py-2 font-normal">{categories.map(c => <option key={c.categoryId} value={c.categoryId}>{c.categoryName}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Asunto<input value={subject} onChange={e => setSubject(e.target.value)} className="rounded-lg border px-3 py-2 font-normal"/></label><label className="grid gap-2 text-sm font-semibold">Oferta<input value={offerText} onChange={e => setOfferText(e.target.value)} className="rounded-lg border px-3 py-2 font-normal"/></label><div className="grid grid-cols-2 gap-3"><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="rounded-lg border px-3 py-2"/><input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} className="rounded-lg border px-3 py-2"/></div><button disabled={busy} className="w-full rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy ? "Analizando..." : "Analizar y previsualizar"}</button></form></section><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Vista previa</h2>{response ? <div className="mt-4 space-y-4"><div className="rounded-lg bg-slate-50 p-4 text-sm"><p><strong>Categoría:</strong> {response.categoryName}</p><p><strong>Destinatarios:</strong> {response.recipients}</p><p><strong>Productos elegidos:</strong> {response.products.map(p => p.name).join(", ")}</p></div><iframe title="Vista previa" srcDoc={preview} className="h-[520px] w-full rounded-lg border"/><button onClick={send} disabled={busy} className="w-full rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-60">Enviar campaña</button></div> : <p className="mt-4 text-sm text-slate-500">Genera una vista previa para ver la selección automática.</p>}</section></div>;
}
